const chameleonColorList = [
  { id: 161, name: "Anodized Red" },
  { id: 162, name: "Anodized Wine" },
  { id: 163, name: "Anodized Purple" },
  { id: 164, name: "Anodized Blue" },
  { id: 165, name: "Anodized Green" },
  { id: 166, name: "Anodized Lime" },
  { id: 167, name: "Anodized Copper" },
  { id: 168, name: "Anodized Bronze" },
  { id: 169, name: "Anodized Champagne" },
  { id: 170, name: "Anodized Gold" },
  { id: 171, name: "Green Blue Flip" },
  { id: 172, name: "Green Red Flip" },
  { id: 173, name: "Green Brown Flip" },
  { id: 174, name: "Green Turquoise Flip" },
  { id: 175, name: "Green Purple Flip" },
  { id: 176, name: "Teal Purple Flip" },
  { id: 177, name: "Turquoise Red Flip" },
  { id: 178, name: "Turquoise Purple Flip" },
  { id: 179, name: "Cyan Purple Flip" },
  { id: 180, name: "Blue Pink Flip" },
  { id: 181, name: "Blue Green Flip" },
  { id: 182, name: "Purple Red Flip" },
  { id: 183, name: "Purple Green Flip" },
  { id: 184, name: "Magenta Green Flip" },
  { id: 185, name: "Magenta Yellow Flip" },
  { id: 186, name: "Burgundy Green Flip" },
  { id: 187, name: "Magenta Cyan Flip" },
  { id: 188, name: "Copper Purple Flip" },
  { id: 189, name: "Magenta Orange Flip" },
  { id: 190, name: "Red Orange Flip" },
  { id: 191, name: "Orange Purple Flip" },
  { id: 192, name: "Orange Blue Flip" },
  { id: 193, name: "White Purple Flip" },
  { id: 194, name: "Red Rainbow Flip" },
  { id: 195, name: "Blue Rainbow Flip" },
  { id: 196, name: "Dark Green Pearl" },
  { id: 197, name: "Dark Teal Pearl" },
  { id: 198, name: "Dark Blue Pearl" },
  { id: 199, name: "Dark Purple Pearl" },
  { id: 200, name: "Oil Slick Pearl" },
  { id: 201, name: "Lit Green Pearl" },
  { id: 202, name: "Lit Blue Pearl" },
  { id: 203, name: "Lit Purple Pearl" },
  { id: 204, name: "Lit Pink Pearl" },
  { id: 205, name: "Offwhite Prisma" },
  { id: 206, name: "Pink Pearl" },
  { id: 207, name: "Yellow Pearl" },
  { id: 208, name: "Green Pearl" },
  { id: 209, name: "Blue Pearl" },
  { id: 210, name: "Cream Pearl" },
  { id: 211, name: "White Prisma" },
  { id: 212, name: "Graphite Prisma" },
  { id: 213, name: "Dark Blue Prisma" },
  { id: 214, name: "Dark Purple Prisma" },
  { id: 215, name: "Hot Pink Prisma" },
  { id: 216, name: "Red Prisma" },
  { id: 217, name: "Green Prisma" },
  { id: 218, name: "Black Prisma" },
  { id: 219, name: "Oil Slick Prisma" },
  { id: 220, name: "Rainbow Prisma" },
  { id: 221, name: "Black Holo" },
  { id: 222, name: "White Holo" },
  { id: 223, name: "YKTA Monochrome" },
  { id: 236, name: "YKTA Chromabera" },
  { id: 240, name: "YKTA Electro" },
  { id: 226, name: "YKTA Sprunk EX" },
  { id: 239, name: "YKTA HSW" },
  { id: 224, name: "YKTA Nite Day" },
  { id: 233, name: "YKTA Sunsets" },
  { id: 227, name: "YKTA Vice City" },
  { id: 228, name: "YKTA Synthwave" },
  { id: 225, name: "YKTA Verlierer2" },
  { id: 238, name: "YKTA Temperatur" },
  { id: 229, name: "YKTA Four Seasons" },
  { id: 234, name: "YKTA The Seven" },
  { id: 230, name: "YKTA M9 Throwback" },
  { id: 231, name: "YKTA Bubblegum" },
  { id: 232, name: "YKTA Full Rainbow" },
  { id: 235, name: "YKTA Kamen Rider" },
  { id: 237, name: "YKTA Christmas" },
  { id: 241, name: "YKTA Monika" },
  { id: 242, name: "YKTA Fubuki" }
];